### ISSUE TITLE
[v1.4] Bug for selecting project and adding task and selecting task

### ISSUE THREAD

**Issue by arhjaye** [CS2113-AY1819S2-T09-3/main#177]
When selecting a project that has no task. Index out of bound exception will occur.
![image](https://user-images.githubusercontent.com/46835688/55667416-8d41a280-588e-11e9-9a98-ffee76be338d.png)

when adding task after the above command is run,  task is added but nullpointerexception will occur
![image](https://user-images.githubusercontent.com/46835688/55667433-cc6ff380-588e-11e9-9988-eb2592ff26cf.png)

when adding another task after the above command is run, task is also added and the nullpointerexception will occur still
![image](https://user-images.githubusercontent.com/46835688/55667444-f88b7480-588e-11e9-96f5-982cdbb2dec4.png)

noting that task 3 is the lastest task that is added (in the pic)
`select 3` or `s 3` will occur null pointer exception
![image](https://user-images.githubusercontent.com/46835688/55667484-85363280-588f-11e9-9033-fb9ccae60165.png)

if you run `select 3` or `s 3` again, it will work normally
![image](https://user-images.githubusercontent.com/46835688/55667500-a72fb500-588f-11e9-8683-0ca0f5c81135.png)

if you run `select 3` or `s 3` again, it will work normally
![image](https://user-images.githubusercontent.com/46835688/55667503-b57dd100-588f-11e9-8201-8d75917b9125.png)

if you run `select 1` or `s 1` , it will run normally
![image](https://user-images.githubusercontent.com/46835688/55667515-d6debd00-588f-11e9-8008-fcc7ea5878b2.png)

if you run `select 2` or `s 2` , it will run normally 
![image](https://user-images.githubusercontent.com/46835688/55667547-2e7d2880-5890-11e9-899d-4814fc646282.png)

if you run `select 3` or `s 3` , null pointer exception will occur still
![image](https://user-images.githubusercontent.com/46835688/55667558-52d90500-5890-11e9-86e5-4dd69eb57b51.png)

**Comment by rachellim10** [comment]
1. add new proj --> proj added
2. select that proj --> selected but _index OOB exception_
3. add new task in that proj --> no error & results box msg was task_added_successfully, BUT the _new task was not displayed on UI_
4. close app and restart
5. repeat steps 1-3; this time step 2 still had _index OOB_, but adding 3 new tasks led to _null ptr exception_ each time (like for Ren Jie)
6. select latest task (task 3) but no error or exception (unlike Ren Jie)
7. subsequent selecting of tasks also no err/exception (unlike Ren Jie)
