### ISSUE TITLE
Bug occured during interaction between Project and Task

### ISSUE THREAD

**Issue by arhjaye** [CS2113-AY1819S2-T09-3/main#97]
right after starting the app
"select 2" followed by "lp" causes this error
![image](https://user-images.githubusercontent.com/46835688/54879480-57ef8a80-4e74-11e9-8b87-852ec3f4613e.png)

"select 1" followed by "lp" does not cause any exception error but darken / brighten does not work as intended
![image](https://user-images.githubusercontent.com/46835688/54879505-9c7b2600-4e74-11e9-9ef1-1e8192b3ef96.png)

"select 1" followed by "listproject" AND "select 2" followed by "listproject"
does not cause any exception error. however in terminal shows "INFO: Project list modified, saving to file." even though no edits were made. I THINK this is a wrong behavior however im not sure. 
![image](https://user-images.githubusercontent.com/46835688/54879556-3b078700-4e75-11e9-861e-d00cb1674ee5.png)

**Comment by arhjaye** [comment]
On project level, using alias of Select, "s" does not work

**Comment by rachellim10** [comment]
"s x" selects project x but does not darken project panel nor display tasks under project x
![image](https://user-images.githubusercontent.com/39293260/54923106-83da4100-4f44-11e9-8441-b6325ecddadc.png)
